# Generated by Django 4.2.4 on 2023-08-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_avail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avail',
            name='fri',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='mon',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='sat',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='sun',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='thr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='tue',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='wed',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
