# Generated by Django 4.2.4 on 2023-08-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verify',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
