# Generated by Django 4.1.7 on 2023-08-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user1_alter_avail_user_alter_meeting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='avail',
            name='mon_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='avail',
            name='mon_start',
            field=models.TimeField(null=True),
        ),
    ]
