# Generated by Django 4.1.7 on 2023-08-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_avail_mon_end_avail_mon_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='avail',
            name='fri_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='avail',
            name='fri_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='avail',
            name='sat_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='avail',
            name='sat_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='avail',
            name='thu_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='avail',
            name='thu_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='avail',
            name='tue_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='avail',
            name='tue_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='avail',
            name='wed_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='avail',
            name='wed_start',
            field=models.TimeField(null=True),
        ),
    ]
