# Generated by Django 4.1.7 on 2023-08-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_avail_fri_end_avail_fri_start_avail_sat_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avail',
            name='sun_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='avail',
            name='sun_start',
            field=models.TimeField(null=True),
        ),
    ]
