# Generated by Django 4.1.7 on 2023-08-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_avail_sun_end_avail_sun_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avail',
            name='fri_end',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='fri_start',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='mon_end',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='mon_start',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='sat_end',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='sat_start',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='sun_end',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='sun_start',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='thu_end',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='thu_start',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='tue_end',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='tue_start',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='wed_end',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='wed_start',
            field=models.TextField(null=True),
        ),
    ]
