# Generated by Django 4.1.7 on 2023-08-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_avail_fri_end_alter_avail_fri_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
