# Generated by Django 4.1.7 on 2023-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_meeting_day_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='mobile',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
