# Generated by Django 4.2.1 on 2023-10-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_weeklyavai_delete_weeklyavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyavai',
            name='available',
        ),
        migrations.RemoveField(
            model_name='weeklyavai',
            name='day',
        ),
        migrations.RemoveField(
            model_name='weeklyavai',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='weeklyavai',
            name='start_time',
        ),
    ]
