# Generated by Django 4.2.1 on 2023-10-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyAvai',
        ),
    ]
