# Generated by Django 4.2.1 on 2023-10-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_delete_weeklyavai'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='creator_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
